package GUI.Administrador.Estudiantes;

/**
 *
 * @author Alexander
 */
public class JFAdmin_EliminarEstudiante extends javax.swing.JFrame {

    private int x;
    private int y;

    public JFAdmin_EliminarEstudiante() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo1 = new javax.swing.JLabel();
        jButtonMinimizar = new javax.swing.JButton();
        jButtonSalirIcon = new javax.swing.JButton();
        jPanelDatoEstudiante = new javax.swing.JPanel();
        jTFBuscar_EliminarEst = new javax.swing.JTextField();
        jLCedula = new javax.swing.JLabel();
        jBEliminar_estudiante = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jPDatosEstudianteEliminar1 = new javax.swing.JPanel();
        jTFCodigo_EliminarEst1 = new javax.swing.JTextField();
        jLabelNom1 = new javax.swing.JLabel();
        jTFNombres_EliminarEst1 = new javax.swing.JTextField();
        jLabelApe1 = new javax.swing.JLabel();
        jTFApellidos_EliminarEst1 = new javax.swing.JTextField();
        jLabelSector1 = new javax.swing.JLabel();
        jTFCelu_EliminarEst1 = new javax.swing.JTextField();
        jLabelCelu1 = new javax.swing.JLabel();
        jTFFacultad_EliminarEst1 = new javax.swing.JTextField();
        jLabelCorre2 = new javax.swing.JLabel();
        jTFCorreo_EliminarEst2 = new javax.swing.JTextField();
        jLabelFacu1 = new javax.swing.JLabel();
        jTFSectorEst_EliminarEst1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabelCorre3 = new javax.swing.JLabel();
        jTFCorreo_EliminarEst3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 16)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(250, 183, 22));
        jLabelTitulo1.setText("ELIMINAR ESTUDIANTE");

        jButtonMinimizar.setBackground(new java.awt.Color(91, 165, 152));
        jButtonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Minimizar 24.png"))); // NOI18N
        jButtonMinimizar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(57, 116, 104)));
        jButtonMinimizar.setPreferredSize(new java.awt.Dimension(24, 24));
        jButtonMinimizar.setRequestFocusEnabled(false);
        jButtonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizarActionPerformed(evt);
            }
        });

        jButtonSalirIcon.setBackground(new java.awt.Color(91, 165, 152));
        jButtonSalirIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButtonSalirIcon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(48, 108, 97)));
        jButtonSalirIcon.setPreferredSize(new java.awt.Dimension(24, 24));
        jButtonSalirIcon.setRequestFocusEnabled(false);
        jButtonSalirIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirIconActionPerformed(evt);
            }
        });

        jPanelDatoEstudiante.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatoEstudiante.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del profesor"));

        jTFBuscar_EliminarEst.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTFBuscar_EliminarEst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFBuscar_EliminarEstKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFBuscar_EliminarEstKeyTyped(evt);
            }
        });

        jLCedula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLCedula.setText("N°Cédula:");

        javax.swing.GroupLayout jPanelDatoEstudianteLayout = new javax.swing.GroupLayout(jPanelDatoEstudiante);
        jPanelDatoEstudiante.setLayout(jPanelDatoEstudianteLayout);
        jPanelDatoEstudianteLayout.setHorizontalGroup(
            jPanelDatoEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatoEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCedula)
                .addGap(85, 85, 85)
                .addComponent(jTFBuscar_EliminarEst, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDatoEstudianteLayout.setVerticalGroup(
            jPanelDatoEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatoEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatoEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFBuscar_EliminarEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCedula))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jBEliminar_estudiante.setForeground(new java.awt.Color(58, 160, 141));
        jBEliminar_estudiante.setText("eliminar");
        jBEliminar_estudiante.setBorder(null);
        jBEliminar_estudiante.setBorderPainted(false);
        jBEliminar_estudiante.setHideActionText(true);
        jBEliminar_estudiante.setMaximumSize(new java.awt.Dimension(89, 32));
        jBEliminar_estudiante.setMinimumSize(new java.awt.Dimension(89, 32));
        jBEliminar_estudiante.setPreferredSize(new java.awt.Dimension(89, 32));
        jBEliminar_estudiante.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jBEliminar_estudianteMouseDragged(evt);
            }
        });
        jBEliminar_estudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBEliminar_estudianteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBEliminar_estudianteMouseExited(evt);
            }
        });
        jBEliminar_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminar_estudianteActionPerformed(evt);
            }
        });

        jBCancelar.setForeground(new java.awt.Color(58, 160, 141));
        jBCancelar.setText("cancelar");
        jBCancelar.setBorder(null);
        jBCancelar.setBorderPainted(false);
        jBCancelar.setHideActionText(true);
        jBCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBCancelar.setMaximumSize(new java.awt.Dimension(89, 32));
        jBCancelar.setMinimumSize(new java.awt.Dimension(89, 32));
        jBCancelar.setPreferredSize(new java.awt.Dimension(89, 32));
        jBCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBCancelarMouseExited(evt);
            }
        });
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jPDatosEstudianteEliminar1.setBackground(new java.awt.Color(255, 255, 255));
        jPDatosEstudianteEliminar1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Eliminar"));

        jTFCodigo_EliminarEst1.setEditable(false);
        jTFCodigo_EliminarEst1.setBackground(new java.awt.Color(255, 255, 255));
        jTFCodigo_EliminarEst1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabelNom1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelNom1.setText("Nombres");

        jTFNombres_EliminarEst1.setEditable(false);
        jTFNombres_EliminarEst1.setBackground(new java.awt.Color(255, 255, 255));
        jTFNombres_EliminarEst1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabelApe1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelApe1.setText("Apellidos");

        jTFApellidos_EliminarEst1.setEditable(false);
        jTFApellidos_EliminarEst1.setBackground(new java.awt.Color(255, 255, 255));
        jTFApellidos_EliminarEst1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabelSector1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelSector1.setText("Nombres Repre.");

        jTFCelu_EliminarEst1.setEditable(false);
        jTFCelu_EliminarEst1.setBackground(new java.awt.Color(255, 255, 255));
        jTFCelu_EliminarEst1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabelCelu1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelCelu1.setText("F. de Nacimiento");

        jTFFacultad_EliminarEst1.setEditable(false);
        jTFFacultad_EliminarEst1.setBackground(new java.awt.Color(255, 255, 255));
        jTFFacultad_EliminarEst1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabelCorre2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelCorre2.setText("Correo elec. Repre.");

        jTFCorreo_EliminarEst2.setEditable(false);
        jTFCorreo_EliminarEst2.setBackground(new java.awt.Color(255, 255, 255));
        jTFCorreo_EliminarEst2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabelFacu1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelFacu1.setText("Apellidos Repre.");

        jTFSectorEst_EliminarEst1.setEditable(false);
        jTFSectorEst_EliminarEst1.setBackground(new java.awt.Color(255, 255, 255));
        jTFSectorEst_EliminarEst1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel21.setText("N° Cédula");

        jLabelCorre3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabelCorre3.setText("Telefono Repre.");

        jTFCorreo_EliminarEst3.setEditable(false);
        jTFCorreo_EliminarEst3.setBackground(new java.awt.Color(255, 255, 255));
        jTFCorreo_EliminarEst3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPDatosEstudianteEliminar1Layout = new javax.swing.GroupLayout(jPDatosEstudianteEliminar1);
        jPDatosEstudianteEliminar1.setLayout(jPDatosEstudianteEliminar1Layout);
        jPDatosEstudianteEliminar1Layout.setHorizontalGroup(
            jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosEstudianteEliminar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDatosEstudianteEliminar1Layout.createSequentialGroup()
                        .addComponent(jLabelCorre3)
                        .addGap(18, 18, 18)
                        .addComponent(jTFCorreo_EliminarEst3))
                    .addGroup(jPDatosEstudianteEliminar1Layout.createSequentialGroup()
                        .addGroup(jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelApe1)
                            .addComponent(jLabelCelu1)
                            .addComponent(jLabelSector1)
                            .addComponent(jLabelFacu1)
                            .addComponent(jLabelCorre2))
                        .addGap(18, 18, 18)
                        .addGroup(jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFCelu_EliminarEst1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(jTFApellidos_EliminarEst1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFCorreo_EliminarEst2)
                            .addComponent(jTFFacultad_EliminarEst1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTFSectorEst_EliminarEst1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPDatosEstudianteEliminar1Layout.createSequentialGroup()
                        .addGroup(jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDatosEstudianteEliminar1Layout.createSequentialGroup()
                                .addComponent(jLabelNom1)
                                .addGap(18, 18, 18))
                            .addGroup(jPDatosEstudianteEliminar1Layout.createSequentialGroup()
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFNombres_EliminarEst1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(jTFCodigo_EliminarEst1))))
                .addContainerGap())
        );
        jPDatosEstudianteEliminar1Layout.setVerticalGroup(
            jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosEstudianteEliminar1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCodigo_EliminarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNombres_EliminarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFApellidos_EliminarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApe1))
                .addGap(6, 6, 6)
                .addGroup(jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCelu_EliminarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCelu1))
                .addGap(6, 6, 6)
                .addGroup(jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFSectorEst_EliminarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSector1))
                .addGap(6, 6, 6)
                .addGroup(jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFFacultad_EliminarEst1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFacu1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCorreo_EliminarEst2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCorre2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDatosEstudianteEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCorreo_EliminarEst3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCorre3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButtonSalirIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelDatoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPDatosEstudianteEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jBEliminar_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSalirIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanelDatoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPDatosEstudianteEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBEliminar_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanelDatoEstudiante.getAccessibleContext().setAccessibleName("Datos del estudiante");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizarActionPerformed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizarActionPerformed

    private void jButtonSalirIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirIconActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirIconActionPerformed

    private void jTFBuscar_EliminarEstKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscar_EliminarEstKeyReleased

    }//GEN-LAST:event_jTFBuscar_EliminarEstKeyReleased

    private void jTFBuscar_EliminarEstKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscar_EliminarEstKeyTyped

    }//GEN-LAST:event_jTFBuscar_EliminarEstKeyTyped

    private void jBEliminar_estudianteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEliminar_estudianteMouseEntered
        this.jBEliminar_estudiante.setText("ELIMINAR");
    }//GEN-LAST:event_jBEliminar_estudianteMouseEntered

    private void jBEliminar_estudianteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEliminar_estudianteMouseExited
        this.jBEliminar_estudiante.setText("eliminar");
    }//GEN-LAST:event_jBEliminar_estudianteMouseExited

    private void jBEliminar_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminar_estudianteActionPerformed

    }//GEN-LAST:event_jBEliminar_estudianteActionPerformed

    private void jBCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseEntered
        this.jBCancelar.setText("CANCELAR");
    }//GEN-LAST:event_jBCancelarMouseEntered

    private void jBCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCancelarMouseExited
        this.jBCancelar.setText("cancelar");
    }//GEN-LAST:event_jBCancelarMouseExited

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed

    }//GEN-LAST:event_jBCancelarActionPerformed
      
    private void jBEliminar_estudianteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBEliminar_estudianteMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEliminar_estudianteMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEliminar_estudiante;
    private javax.swing.JButton jButtonMinimizar;
    private javax.swing.JButton jButtonSalirIcon;
    private javax.swing.JLabel jLCedula;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabelApe1;
    private javax.swing.JLabel jLabelCelu1;
    private javax.swing.JLabel jLabelCorre2;
    private javax.swing.JLabel jLabelCorre3;
    private javax.swing.JLabel jLabelFacu1;
    private javax.swing.JLabel jLabelNom1;
    private javax.swing.JLabel jLabelSector1;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JPanel jPDatosEstudianteEliminar1;
    private javax.swing.JPanel jPanelDatoEstudiante;
    public static javax.swing.JTextField jTFApellidos_EliminarEst1;
    public static javax.swing.JTextField jTFBuscar_EliminarEst;
    public static javax.swing.JTextField jTFCelu_EliminarEst1;
    public static javax.swing.JTextField jTFCodigo_EliminarEst1;
    public static javax.swing.JTextField jTFCorreo_EliminarEst2;
    public static javax.swing.JTextField jTFCorreo_EliminarEst3;
    public static javax.swing.JTextField jTFFacultad_EliminarEst1;
    public static javax.swing.JTextField jTFNombres_EliminarEst1;
    public static javax.swing.JTextField jTFSectorEst_EliminarEst1;
    // End of variables declaration//GEN-END:variables
}
