/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Administrador.General;

import Negocio.Conexion;
import Negocio.Correo;
import javax.swing.JTextArea;

/**
 *
 * @author Alexander
 */
public class JFSoporteTecnico extends javax.swing.JFrame {
  
    String SQL;
    Conexion con = new Conexion();    
    String titulo = null;
    String mensaje = null;
    String tabla = "Admins";
    public JFSoporteTecnico() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTFBuscarCedula = new javax.swing.JTextField();
        jTFCorreo = new javax.swing.JTextField();
        jBEnviar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTASoporteT = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFBuscarCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFBuscarCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFBuscarCedulaKeyTyped(evt);
            }
        });
        jPanel1.add(jTFBuscarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 70, 30));
        jPanel1.add(jTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 210, 30));

        jBEnviar.setBackground(new java.awt.Color(255, 225, 153));
        jBEnviar.setText("ENVIAR");
        jBEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 170, 30));

        jBSalir.setBackground(new java.awt.Color(255, 225, 153));
        jBSalir.setText("SALIR");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, 170, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Número de Cédula:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 110, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Correo Electrónico:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, 30));

        jTASoporteT.setColumns(20);
        jTASoporteT.setRows(5);
        jScrollPane1.setViewportView(jTASoporteT);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 510, 200));

        jLabel10.setFont(new java.awt.Font("Eras Demi ITC", 2, 12)); // NOI18N
        jLabel10.setText("¡Tu experiencia cuenta! Estamos aquí para brindarte el mejor soporte técnico posible. ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 510, 30));

        jLabel12.setFont(new java.awt.Font("Eras Demi ITC", 2, 12)); // NOI18N
        jLabel12.setText("te animamos a que nos lo compartas. ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 420, -1));

        jLabel11.setFont(new java.awt.Font("Eras Demi ITC", 2, 12)); // NOI18N
        jLabel11.setText("Si has encontrado algún problema o dificultad al interactuar con nuestro sistema, ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 400, 30));

        jLabel6.setFont(new java.awt.Font("Eras Demi ITC", 2, 18)); // NOI18N
        jLabel6.setText("Cuéntanos tu problema");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 210, 30));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jLabel1.setText(" SOPORTE TECNICO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 350, 50));

        jLabel3.setBackground(new java.awt.Color(204, 255, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vector.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 80, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rectangle 29.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rectangle 30.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 130, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ellipse 48.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 390, 200));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ellipse 48.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 390, 200));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ellipse 47.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, 170));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ellipse 2.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 650, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        this.dispose();
        JPHome mainFrame = new JPHome();
        mainFrame.setVisible(true);
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarActionPerformed
        String mensajeDetallado = jTASoporteT.getText();
        String correoEmisor = jTFCorreo.getText();
        Correo correo = new Correo();
        correo.enviarCorreos(mensajeDetallado, "soportetecnicomousai@gmail.com");
            
    }//GEN-LAST:event_jBEnviarActionPerformed

    private void jTFBuscarCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscarCedulaKeyReleased
        String parametroBusqueda = this.jTFBuscarCedula.getText();
        if (parametroBusqueda.length() == 10) {
            this.SQL = "SELECT p.Correo FROM Personas p WHERE Cedula LIKE '%" + parametroBusqueda + "%';";
            con.despliegueFields(SQL, "Admins", null, null, null, jTFCorreo, null, null, null, null, "recuperar");
        } else {
            limpiarCampos();
        }        
    }//GEN-LAST:event_jTFBuscarCedulaKeyReleased

    private void jTFBuscarCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBuscarCedulaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFBuscarCedulaKeyTyped

    public void limpiarCampos() {
        jTFCorreo.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEnviar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTASoporteT;
    private javax.swing.JTextField jTFBuscarCedula;
    private javax.swing.JTextField jTFCorreo;
    // End of variables declaration//GEN-END:variables
}
